"""Embed the shared HMI icon set into web demo pages as an inline SVG sprite.

Source of truth: app/hmi/presentation/icons/svg/*.svg. The sprite is written
between the icon-sprite markers of each target page; everything else in the
page is left untouched.

Usage:
    python tools/build_icon_sprite.py            # update the default page(s)
    python tools/build_icon_sprite.py --check    # exit 1 if a page is stale
    python tools/build_icon_sprite.py PAGE.html  # update specific page(s)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ICON_DIR = ROOT / "app" / "hmi" / "presentation" / "icons" / "svg"
DEFAULT_PAGES = [ROOT / "docs" / "images" / "theme" / "hmi-web-demo.html"]
BEGIN = "<!-- icon-sprite:begin (generated by tools/build_icon_sprite.py; do not edit) -->"
END = "<!-- icon-sprite:end -->"
NAME = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
ROOT_SVG = re.compile(r"^\s*<svg\b([^>]*)>(.*)</svg>\s*$", re.S)
FORBIDDEN = re.compile(r"<(script|style|image|foreignObject)\b|\bon\w+\s*=|href\s*=", re.I)
# Stroke defaults sit on every symbol so a <use> clone renders the same anywhere; filled shapes override fill.
STROKE = 'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"'
SPRITE_OPEN = '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">'


def icon_symbols() -> list[str]:
    symbols = []
    for path in sorted(ICON_DIR.glob("*.svg")):
        name = path.stem
        if not NAME.match(name):
            raise SystemExit(f"{path.name}: icon names are lower-case and hyphenated")
        match = ROOT_SVG.match(path.read_text(encoding="utf-8"))
        if not match:
            raise SystemExit(f"{path.name}: expected a single <svg> root element")
        attributes, body = match.groups()
        if 'viewBox="0 0 24 24"' not in attributes:
            raise SystemExit(f"{path.name}: viewBox must be 0 0 24 24")
        if FORBIDDEN.search(body):
            raise SystemExit(f"{path.name}: scripts, styles, links and embedded images are not allowed")
        symbols.append(f'<symbol id="i-{name}" viewBox="0 0 24 24" {STROKE}>{body.strip()}</symbol>')
    if not symbols:
        raise SystemExit(f"no icons found in {ICON_DIR}")
    return symbols


def sprite() -> str:
    return f"{BEGIN}\n{SPRITE_OPEN}{''.join(icon_symbols())}</svg>\n{END}"


def render(page: str, block: str) -> str:
    if BEGIN in page and END in page:
        start, end = page.index(BEGIN), page.index(END) + len(END)
        return page[:start] + block + page[end:]
    marker = page.find("<body>")
    if marker < 0:
        raise SystemExit("page has no <body> to host the sprite")
    marker += len("<body>")
    return page[:marker] + "\n" + block + page[marker:]


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("pages", nargs="*", type=Path, help="HTML pages to update (default: the style preview)")
    parser.add_argument("--check", action="store_true", help="report stale pages without writing")
    options = parser.parse_args(arguments)
    block, stale = sprite(), []
    for page_path in options.pages or DEFAULT_PAGES:
        current = page_path.read_text(encoding="utf-8")
        updated = render(current, block)
        if updated == current:
            continue
        if options.check:
            stale.append(page_path)
        else:
            page_path.write_text(updated, encoding="utf-8", newline="")
            print(f"updated {page_path}")
    for page_path in stale:
        print(f"stale icon sprite: {page_path}", file=sys.stderr)
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
